# ./src/debugger3.py -i data/projs/flowcert/base.z3/permission.14.smt2
./src/debugger3.py -i data/projs/splinterdb/base.z3/allocation_layer__LikesBetree_v__LikesBetree.3.smt2
./src/debugger3.py -i data/projs/splinterdb/base.z3/allocation_layer__LikesBetree_v.18.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__helper_invariants__proof__lemma_eventually_always_no_delete_resource_request_msg_in_flight.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__helper_invariants__validation.3.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__liveness__stateful_set_match__lemma_from_after_get_stateful_set_step_to_after_update_stateful_set_step.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__helper_invariants__proof.2.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit__proof__helper_invariants__validation.3.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__helper_invariants__zookeeper_api__lemma_zk_request_implies_step_helper.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit__proof__liveness__resource_match__lemma_from_after_get_resource_step_to_after_update_resource_step.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__liveness__stateful_set_match.2.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit_config__proof__liveness__resource_match.6.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__helper_invariants__proof__lemma_eventually_always_every_resource_create_request_implies_at_after_create_resource_step.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit__proof__liveness__daemon_set_match__lemma_from_after_get_daemon_set_step_to_after_update_daemon_set_step.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__liveness__resource_match__lemma_from_after_get_resource_step_to_after_update_resource_step.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit_config__proof__liveness__resource_match__lemma_from_after_get_resource_step_to_after_create_resource_step.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__liveness__resource_match.1.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__helper_invariants__proof__lemma_eventually_always_object_in_response_at_after_create_resource_step_is_same_as_etcd.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__liveness__stateful_set_match__lemma_stateful_set_state_matches_at_after_update_stateful_set_step.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__helper_invariants__validation__lemma_always_stateful_set_in_create_request_msg_satisfies_unchangeable.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__helper_invariants__proof__lemma_always_no_update_status_request_msg_in_flight_of_except_stateful_set.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit_config__proof__liveness__resource_match.5.smt2
./src/debugger3.py -i data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit__proof__helper_invariants__proof.9.smt2
./src/debugger3.py -i data/projs/v_systems/base.z3/mimalloc--page_organization__PageOrg.69.smt2
./src/debugger3.py -i data/projs/v_systems/base.z3/noderep--spec__cyclicbuffer.3.smt2
./src/debugger3.py -i data/projs/v_systems/base.z3/mimalloc--bin_sizes.23.smt2
./src/debugger3.py -i data/projs/v_systems/base.z3/mimalloc--page_organization__PageOrg__impl__4__merge_with_before_ll_inv_valid_unused.smt2
./src/debugger3.py -i data/projs/v_systems/base.z3/noderep--spec__cyclicbuffer.5.smt2
./src/debugger3.py -i data/projs/v_systems/base.z3/mimalloc--commit_segment.1.smt2
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/boot__init__e820_init.2.smt2 
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/security__monitor.21.smt2 
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/vbox__vbox.5.smt2 
# ./src/debugger3.py -i data/projs/verismo.dedup/base.z3/arch__ptram__ptram_p2.smt2
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/bsp__ap.3.smt2 
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/snp__cpuid.17.smt2 
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/snp__ghcb__proto_page.141.smt2 
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/pgtable_e__pte.20.smt2 
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/vbox__vbox.4.smt2 
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/boot__init__e820_init_alloc.1.smt2 
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/allocator__linkedlist.10.smt2 
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/pgtable_e__pte.18.smt2 
./src/debugger3.py -i data/projs/verismo.dedup/base.z3/boot__init__e820_init.4.smt2