# files under Impl/
IMPL_FILE_MAP = {"AllocationReport": (["AllocationReport.i.dfy"], ["AllocationReport.i.dfy"]),
"BlockAllocator": (["BlockAllocatorImpl.i.dfy", "BlockAllocatorModel.i.dfy"], ["BlockAllocatorImpl.i.dfy", "BlockAllocatorModel.i.dfy"]),
"Bookkeeping": (["BookkeepingImpl.i.dfy", "BookkeepingModel.i.dfy"], ["BookkeepingImpl.i.dfy", "BookkeepingModel.i.dfy"]),
"BucketGenerator": (["BucketGeneratorImpl.i.dfy", "BucketGeneratorModel.i.dfy"], ["BucketGeneratorImpl.i.dfy", "BucketGeneratorModel.i.dfy"]),
"BucketSuccessorLoop": (["BucketSuccessorLoopImpl.i.dfy", "BucketSuccessorLoopModel.i.dfy"], ["BucketSuccessorLoopImpl.i.dfy", "BucketSuccessorLoopModel.i.dfy"]),
"Bundle": (["Bundle.i.dfy"], ["Bundle.i.dfy"]),
"Cache": (["CacheImpl.i.dfy"], ["CacheImpl.i.dfy"]),
"Committer":(["CommitterAppendImpl.i.dfy", "CommitterAppendModel.i.dfy", "CommitterCommitImpl.i.dfy", "CommitterCommitModel.i.dfy", "CommitterImpl.i.dfy", "CommitterInitImpl.i.dfy","CommitterInitModel.i.dfy", "CommitterModel.i.dfy", "CommitterReplayImpl.i.dfy", "CommitterReplayModel.i.dfy"], ["CommitterImpl.i.dfy"]),
"Coordination": (["CoordinationImpl.i.dfy", "CoordinationModel.i.dfy"], ["CoordinationImpl.i.dfy"]),
"Dealloc": (["DeallocImpl.i.dfy", "DeallocModel.i.dfy"], ["DeallocImpl.i.dfy"]),
"DiskOp": (["DiskOpImpl.i.dfy", "DiskOpModel.i.dfy"], ["DiskOpImpl.i.dfy", "DiskOpModel.i.dfy"]),
"Evict": (["EvictImpl.i.dfy", "EvictModel.i.dfy"], ["EvictImpl.i.dfy"]),
"Flush": (["FlushImpl.i.dfy", "FlushModel.i.dfy"], ["FlushImpl.i.dfy", "FlushModel.i.dfy"]),
"FlushPolicy": (["FlushPolicyImpl.i.dfy", "FlushPolicyModel.i.dfy"], ["FlushPolicyImpl.i.dfy", "FlushPolicyModel.i.dfy"]),
"Full": (["FullImpl.i.dfy"], ["FullImpl.i.dfy"]),
"Grow": (["GrowImpl.i.dfy", "GrowModel.i.dfy"], ["GrowImpl.i.dfy", "GrowModel.i.dfy"]),
"HandleReadResponse": (["HandleReadResponseImpl.i.dfy", "HandleReadResponseModel.i.dfy"], ["HandleReadResponseImpl.i.dfy", "HandleReadResponseModel.i.dfy"]),
"HandleWriteResponse": (["HandleWriteResponseImpl.i.dfy", "HandleWriteResponseModel.i.dfy"], ["HandleWriteResponseImpl.i.dfy"]),
"IO": (["IOImpl.i.dfy", "IOModel.i.dfy"], ["IOImpl.i.dfy", "IOModel.i.dfy"]),
"IndirectionTable": (["IndirectionTableImpl.i.dfy", "IndirectionTableModel.i.dfy"], ["IndirectionTable.i.dfy"]),
"Insert": (["InsertImpl.i.dfy", "InsertModel.i.dfy"], ["InsertImpl.i.dfy", "InsertModel.i.dfy"]),
"Journalist": (["JournalistImpl.i.dfy", "JournalistModel.i.dfy"], ["JournalistImpl.i.dfy"]),
"JournalistMarshalling": (["JournalistMarshallingImpl.i.dfy", "JournalistMarshallingModel.i.dfy"], ["JournalistMarshallingImpl.i.dfy", "JournalistMarshallingModel.i.dfy"]),
"JournalistParsing": (["JournalistParsingImpl.i.dfy"], ["JournalistParsingImpl.i.dfy"]),
"Leaf": (["LeafImpl.i.dfy", "LeafModel.i.dfy"], ["LeafImpl.i.dfy", "LeafModel.i.dfy"]),
"Main": (["Main.s.dfy"], ["Main.s.dfy"]),
"MainDiskIOHandler": (["MainDiskIOHandler.s.dfy"], ["MainDiskIOHandler.s.dfy"]),
"MainHandlers": (["MainHandlers.i.dfy"], ["MainHandlers.i.dfy"]),
"Mkfs": (["Mkfs.i.dfy", "MkfsModel.i.dfy"], ["Mkfs.i.dfy", "MkfsModel.i.dfy"]),
"Node": (["NodeImpl.i.dfy", "NodeModel.i.dfy"], ["NodeImpl.i.dfy"]),
"Query": (["QueryImpl.i.dfy", "QueryModel.i.dfy"], ["QueryImpl.i.dfy", "QueryModel.i.dfy"]),
"Split": (["SplitImpl.i.dfy", "SplitModel.i.dfy"], ["SplitImpl.i.dfy", "SplitModel.i.dfy"]),
"State": (["StateImpl.i.dfy", "StateModel.i.dfy"], ["StateBCImpl.i.dfy", "StateSectorImpl.i.dfy"]),
"Succ": (["SuccImpl.i.dfy", "SuccModel.i.dfy"], ["SuccImpl.i.dfy", "SuccModel.i.dfy"]),
"Sync": (["SyncImpl.i.dfy", "SyncModel.i.dfy"], ["SyncImpl.i.dfy"])}

# impl files under lib/DataStructures
DS_FILE_MAP = {
    "Bitmap": (["BitmapImpl.i.dfy", "BitmapModel.i.dfy"],["BitmapImpl.i.dfy", "BitmapModel.i.dfy"]),
    "Btree": (["BtreeModel.i.dfy", "KMBtree.i.dfy", "MutableBtree.i.dfy"], ["BtreeModel.i.dfy", "KMBtree.i.dfy", "MutableBtree.i.dfy"]),
    # "Btree": (["KMBtree.i.dfy"], ["KMBtree.i.dfy"]),
    "Lru": (["LruImpl.i.dfy", "LruModel.i.dfy"], ["LinearLru.i.dfy", "LruModel.i.dfy", "LinearDList.i.dfy", "LinearUSeq.i.dfy"]),
    "Map": (["MutableMapImpl.i.dfy", "MutableMapModel.i.dfy"], ["LinearMutableMap.i.dfy", "LinearMutableMapBase.i.dfy", "LinearContentMutableMap.i.dfy"])
}

# impl files under lib/Marshalling
MARSHALLING_FILE_MAP = {
    "Marshalling": (
        ["GenericMarshalling.i.dfy", "MarshallingImpl.i.dfy", "MarshallingModel.i.dfy", "Maps.i.dfy", "Native.s.dfy", "Seqs.i.dfy", "Util.i.dfy"],
        ["GenericMarshalling.i.dfy", "MarshallingImpl.i.dfy", "MarshallingModel.i.dfy", "Maps.i.dfy", "Native.s.dfy", "Seqs.i.dfy", "Util.i.dfy"],
    )
}

# impl files under lib/Buckets
BUCKETS_FILE_MAP = {
    "Bucket": (["BucketImpl.i.dfy", "BucketIteratorModel.i.dfy"], ["BucketImpl.i.dfy", "BucketIteratorModel.i.dfy"]),
    "KV": (["KMBPKVOps.i.dfy"], ["LKMBPKVOps.i.dfy"]),
    "Packed": (["PackedKV.i.dfy", "PackedKVMarshalling.i.dfy","PackedStringArray.i.dfy", "PackedStringArrayMarshalling.i.dfy"], ["PackedKV.i.dfy", "PackedKVMarshalling.i.dfy","PackedStringArray.i.dfy","PackedStringArrayMarshalling.i.dfy"])
}

FILE_MAP = dict()
FILE_MAP.update(IMPL_FILE_MAP)
FILE_MAP.update(DS_FILE_MAP)
FILE_MAP.update(MARSHALLING_FILE_MAP)
FILE_MAP.update(BUCKETS_FILE_MAP)

COMPONENT_MAP = {
    "TreeOps": ["BucketGenerator", "BucketSuccessorLoop", "Flush", "Grow", "Insert", "Leaf", "Node", "Query", "Split", "Succ", ],
    "Journal": ["Journalist", "JournalistMarshalling", "JournalistParsing", ],
    "LookupTable": ["Bookkeeping","Dealloc", "Evict", "IndirectionTable", ],
    "IO": ["IO", "HandleReadResponse", "HandleWriteResponse", "Full", "DiskOp", "MainDiskIOHandler", "Sync", "Committer"],
    "SystemCoord.": ["State", "Mkfs", "Coordination", "FlushPolicy"],
    "Buckets": ["Bucket", "KV", "Packed"],
    "LibDS": ["Bitmap", "Btree", "Lru", "Map"],
    "Other":["AllocationReport", "BlockAllocator", "Marshalling", "Cache", "Main", "MainHandlers", "Bundle"]
}

CHANGES_MAP = {
    "Linear Only": ["AllocationReport", "BlockAllocator", "Bookkeeping", "BucketGenerator", "BucketSuccessorLoop", "Bundle", 
        "DiskOp", "Flush", "FlushPolicy", "Full", "Grow", "HandleReadResponse", "IO", "Insert", "JournalistParsing", "JournalistMarshalling",
        "Leaf", "Main", "MainDiskIOHandler", "MainHandlers", "Mkfs", "Query", "Split", "Succ", "Bitmap", "Btree", "Marshalling","Bucket","KV"],
    "Linear & Model/Impl Merge": ["Committer", "Coordination", "Dealloc", "Evict", "HandleWriteResponse", "IndirectionTable", "Journalist", "Node", "State", "Sync"],
    "Linear & Impl Changes": ["Cache", "Map", "Lru"],
    "Unchanged": ["Packed"]
}

REPO_NAMES = ["veribetrkv-dynamic-frames", "veribetrkv-linear"]

# PER_FILE_JSON = "file_time.json"
# PER_PROC_JSON = "proc_time.json"

DF_FILES = ["Betree-Betree.i.dfy",
"Betree-BetreeInv.i.dfy",
"Betree-Betree_Refines_Map.i.dfy",
"Betree-BetreeSpec.i.dfy",
"Betree-BlockInterface.i.dfy",
"Betree-Graph.i.dfy",
"Betree-Transactable.i.dfy",
"BlockCacheSystem-AsyncSectorDiskModelTypes.i.dfy",
"BlockCacheSystem-BetreeCache.i.dfy",
"BlockCacheSystem-BetreeJournalSystem.i.dfy",
"BlockCacheSystem-BetreeJournalSystem_Refines_CompositeView.i.dfy",
"BlockCacheSystem-BetreeJournalSystem_Refines_ThreeStateVersionedMap.i.dfy",
"BlockCacheSystem-BetreeSystem.i.dfy",
"BlockCacheSystem-BetreeSystem_Refines_StatesViewMap.i.dfy",
"BlockCacheSystem-BetreeSystem_Refines_StatesViewPivotBetree.i.dfy",
"BlockCacheSystem-BlockCache.i.dfy",
"BlockCacheSystem-BlockDisk.i.dfy",
"BlockCacheSystem-BlockJournalCache.i.dfy",
"BlockCacheSystem-BlockJournalDisk.i.dfy",
"BlockCacheSystem-BlockSystem.i.dfy",
"BlockCacheSystem-BlockSystem_Refines_StatesView.i.dfy",
"BlockCacheSystem-DiskLayout.i.dfy",
"BlockCacheSystem-JournalCache.i.dfy",
"BlockCacheSystem-JournalDisk.i.dfy",
"BlockCacheSystem-JournalInterval.i.dfy",
"BlockCacheSystem-JournalRange.i.dfy",
"BlockCacheSystem-JournalSystem.i.dfy",
"BlockCacheSystem-JournalSystem_Refines_JournalView.i.dfy",
"BlockCacheSystem-SectorType.i.dfy",
"ByteBlockCacheSystem-AsyncDiskModel.s.dfy",
"ByteBlockCacheSystem-ByteCache.i.dfy",
"ByteBlockCacheSystem-ByteSystem.i.dfy",
"ByteBlockCacheSystem-ByteSystem_Refines_BetreeJournalSystem.i.dfy",
"ByteBlockCacheSystem-ByteSystem_Refines_ThreeStateVersionedMap.i.dfy",
"ByteBlockCacheSystem-InterpretationDiskContents.i.dfy",
"ByteBlockCacheSystem-InterpretationDisk.i.dfy",
"ByteBlockCacheSystem-InterpretationDiskOps.i.dfy",
"ByteBlockCacheSystem-JournalBytes.i.dfy",
"ByteBlockCacheSystem-Marshalling.i.dfy",
"Impl-AllocationReport.i.dfy",
"Impl-BlockAllocatorImpl.i.dfy",
"Impl-BlockAllocatorModel.i.dfy",
"Impl-BookkeepingImpl.i.dfy",
"Impl-BookkeepingModel.i.dfy",
"Impl-BucketGeneratorImpl.i.dfy",
"Impl-BucketGeneratorModel.i.dfy",
"Impl-BucketSuccessorLoopImpl.i.dfy",
"Impl-BucketSuccessorLoopModel.i.dfy",
"Impl-Bundle.i.dfy",
"Impl-CacheImpl.i.dfy",
"Impl-CommitterAppendImpl.i.dfy",
"Impl-CommitterAppendModel.i.dfy",
"Impl-CommitterCommitImpl.i.dfy",
"Impl-CommitterCommitModel.i.dfy",
"Impl-CommitterImpl.i.dfy",
"Impl-CommitterInitImpl.i.dfy",
"Impl-CommitterInitModel.i.dfy",
"Impl-CommitterModel.i.dfy",
"Impl-CommitterReplayImpl.i.dfy",
"Impl-CommitterReplayModel.i.dfy",
"Impl-CoordinationImpl.i.dfy",
"Impl-CoordinationModel.i.dfy",
"Impl-DeallocImpl.i.dfy",
"Impl-DeallocModel.i.dfy",
"Impl-DiskOpImpl.i.dfy",
"Impl-DiskOpModel.i.dfy",
"Impl-EvictImpl.i.dfy",
"Impl-EvictModel.i.dfy",
"Impl-FlushImpl.i.dfy",
"Impl-FlushModel.i.dfy",
"Impl-FlushPolicyImpl.i.dfy",
"Impl-FlushPolicyModel.i.dfy",
"Impl-FullImpl.i.dfy",
"Impl-GrowImpl.i.dfy",
"Impl-GrowModel.i.dfy",
"Impl-HandleReadResponseImpl.i.dfy",
"Impl-HandleReadResponseModel.i.dfy",
"Impl-HandleWriteResponseImpl.i.dfy",
"Impl-HandleWriteResponseModel.i.dfy",
"Impl-IndirectionTableImpl.i.dfy",
"Impl-IndirectionTableModel.i.dfy",
"Impl-InsertImpl.i.dfy",
"Impl-InsertModel.i.dfy",
"Impl-IOImpl.i.dfy",
"Impl-IOModel.i.dfy",
"Impl-JournalistImpl.i.dfy",
"Impl-JournalistMarshallingImpl.i.dfy",
"Impl-JournalistMarshallingModel.i.dfy",
"Impl-JournalistModel.i.dfy",
"Impl-JournalistParsingImpl.i.dfy",
"Impl-LeafImpl.i.dfy",
"Impl-LeafModel.i.dfy",
"Impl-MainDiskIOHandler.s.dfy",
"Impl-MainHandlers.i.dfy",
"Impl-Main.s.dfy",
"Impl-MarshallingImpl.i.dfy",
"Impl-MarshallingModel.i.dfy",
"Impl-Mkfs.i.dfy",
"Impl-MkfsModel.i.dfy",
"Impl-NodeImpl.i.dfy",
"Impl-NodeModel.i.dfy",
"Impl-QueryImpl.i.dfy",
"Impl-QueryModel.i.dfy",
"Impl-SplitImpl.i.dfy",
"Impl-SplitModel.i.dfy",
"Impl-StateImpl.i.dfy",
"Impl-StateModel.i.dfy",
"Impl-SuccImpl.i.dfy",
"Impl-SuccModel.i.dfy",
"Impl-SyncImpl.i.dfy",
"Impl-SyncModel.i.dfy",
"lib-Base-Arithmetic.s.dfy",
"lib-Base-Arrays.i.dfy",
"lib-Base-BitsetLemmas.i.dfy",
"lib-Base-Crypto.s.dfy",
"lib-Base-DebugAccumulator.i.dfy",
"lib-Base-KeyType.s.dfy",
"lib-Base-Maps.s.dfy",
"lib-Base-MathAxioms.s.dfy",
"lib-Base-mathematics.i.dfy",
"lib-Base-Message.i.dfy",
"lib-Base-Multisets.i.dfy",
"lib-Base-NativeArrays.s.dfy",
"lib-Base-NativeBenchmarking.s.dfy",
"lib-Base-NativeTypes.s.dfy",
"lib-Base-Option.s.dfy",
"lib-Base-PackedIntsLib.i.dfy",
"lib-Base-PackedInts.s.dfy",
"lib-Base-SeqComparison.s.dfy",
"lib-Base-sequences.i.dfy",
"lib-Base-SetBijectivity.i.dfy",
"lib-Base-Sets.i.dfy",
"lib-Base-total_order.i.dfy",
"lib-Base-total_order_impl.i.dfy",
"lib-Buckets-BucketImpl.i.dfy",
"lib-Buckets-BucketIteratorModel.i.dfy",
"lib-Buckets-BucketModel.i.dfy",
"lib-Buckets-BucketsLib.i.dfy",
"lib-Buckets-BucketWeights.i.dfy",
"lib-Buckets-KMBPKVOps.i.dfy",
"lib-Buckets-PackedKV.i.dfy",
"lib-Buckets-PackedKVMarshalling.i.dfy",
"lib-Buckets-PackedStringArray.i.dfy",
"lib-Buckets-PackedStringArrayMarshalling.i.dfy",
"lib-Buckets-PivotsLib.i.dfy",
"lib-DataStructures-BitmapImpl.i.dfy",
"lib-DataStructures-BitmapModel.i.dfy",
"lib-DataStructures-BtreeModel.i.dfy",
"lib-DataStructures-KMBtree.i.dfy",
"lib-DataStructures-LruImpl.i.dfy",
"lib-DataStructures-LruModel.i.dfy",
"lib-DataStructures-MutableBtreeBulkOperations.i.dfy",
"lib-DataStructures-MutableBtree.i.dfy",
"lib-DataStructures-MutableMapImpl.i.dfy",
"lib-DataStructures-MutableMapModel.i.dfy",
"lib-Marshalling-GenericMarshalling.i.dfy",
"lib-Marshalling-Maps.i.dfy",
"lib-Marshalling-Math.i.dfy",
"lib-Marshalling-Seqs.i.dfy",
"lib-Marshalling-Util.i.dfy",
"lib-Math-bases.i.dfy",
"lib-Math-LinearCongruentialGenerator.s.dfy",
"MapSpec-Journal.i.dfy",
"MapSpec-MapSpec.s.dfy",
"MapSpec-ThreeStateVersionedMap.s.dfy",
"MapSpec-ThreeStateVersioned.s.dfy",
"MapSpec-TSJ.i.dfy",
"MapSpec-TSJMap.i.dfy",
"MapSpec-TSJMap_Refines_ThreeStateVersionedMap.i.dfy",
"MapSpec-UI.s.dfy",
"MapSpec-UIStateMachine.s.dfy",
"PivotBetree-Bounds.i.dfy",
"PivotBetree-PivotBetree.i.dfy",
"PivotBetree-PivotBetree_Refines_Betree.i.dfy",
"PivotBetree-PivotBetree_Refines_Map.i.dfy",
"PivotBetree-PivotBetreeSpec.i.dfy",
"PivotBetree-PivotBetreeSpecRefinement.i.dfy",
"PivotBetree-PivotBetreeSpecWFNodes.i.dfy",
"PivotBetree-StatesViewPivotBetree.i.dfy",
"PivotBetree-StatesViewPivotBetree_Refines_StatesViewMap.i.dfy",
"Versions-CompositeView.i.dfy",
"Versions-CompositeView_Refines_ThreeStateVersionedMap.i.dfy",
"Versions-CompositeView_Refines_TSJMap.i.dfy",
"Versions-JournalView.i.dfy",
"Versions-StatesView.i.dfy",
"Versions-StatesViewMap.i.dfy",
"Versions-VOp.i.dfy"]