../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_fvbkv_z3_clean--PivotBetree-PivotBetreeSpecWFNodes.i.dfy.Impl__PivotBetreeSpecWFNodes.__default.BucketListWellMarshalledCutoffNodeAndKeepRight.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-allocate_page.gen.dfyImpl___module.__default.va__lemma__allocate__page__success.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-attest.gen.dfyImpl___module.__default.va__lemma__svc__returning__attest__inner.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-attest_input.gen.dfyImpl___module.__default.va__lemma__arrange__user__regs__in__memory.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-entry.gen.dfyImpl___module.__default.va__lemma__stack__banked__regs1.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-entry.gen.dfyImpl___module.__default.va__lemma__unstack__banked__regs.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-entry.i.dfyImpl___module.__default.lemma__userExecutionPreservesPrivState.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-finalise.gen.dfyImpl___module.__default.va__lemma__kom__smc__finalise.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-init_addrspace.gen.dfyImpl___module.__default.va__lemma__kom__smc__init__addrspace.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-init_l2ptable.gen.dfyImpl___module.__default.lemma__ARM__L1PTE__Dual__n.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-init_l2ptable.gen.dfyImpl___module.__default.va__lemma__init__l2ptable__success.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-init_l2ptable.gen.dfyImpl___module.__default.va__lemma__install__l1ptes.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-map_common.gen.dfyImpl___module.__default.va__lemma__init__secure__page.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-map_common.gen.dfyImpl___module.__default.va__lemma__is__valid__mapping__target_k.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-map_common.gen.dfyImpl___module.__default.va__lemma__update__l2pte.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-map_secure.gen.dfyImpl___module.__default.va__lemma__kom__smc__map__secure.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-map_secure.gen.dfyImpl___module.__default.va__lemma__map__secure__success.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-map_secure.gen.dfyImpl___module.__default.va__lemma__map__secure__update.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-map_utils.gen.dfyCheckWellformed___module.__default.va__lemma__kom__smc__map__measure__sha.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-memset.gen.dfyImpl___module.__default.va__lemma__memcpy__bare.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-psrbits.i.dfyImpl___module.__default.lemma__update__psr__f.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-secprop-conf_ni_entry.i.dfyImpl___module.__default.lemma__updateUserPages__conf__not__atkr.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-secprop-conf_ni_entry.i.dfyImpl___module.__default.lemma__userspaceExec__atkr.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-secprop-conf_ni_entry.i.dfyImpl___module.__default.lemma__validEnclaveStepPrime__conf__not__atkr__retnondet.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-secprop-integ_ni_entry.i.dfyImpl___module.__default.lemma__enter__loweq__pdb__not__obs.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-sha-hmac.gen.dfyImpl___module.__default.va__lemma__hmac.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-sha-sha256.i.dfyImpl___module.__default.lemma__ConcatenateSeqs__Adds.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-sha-sha256.i.dfyImpl___module.__default.lemma__InputHelper.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-smcapi.s.dfyCheckWellformed___module.__default.contentsOfPhysPage.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-smc_handler.gen.dfyImpl___module.__default.va__lemma__smc__handler__inner.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-stop.gen.dfyImpl___module.__default.va__lemma__kom__smc__stop.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-svc_handlers.gen.dfyImpl___module.__default.lemma__svc__returning__verify__step1__helper.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-svc_handlers.gen.dfyImpl___module.__default.va__lemma__existing__va__ok.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-svc_handlers.gen.dfyImpl___module.__default.va__lemma__get__cur__addrspace.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-svc_handlers.gen.dfyImpl___module.__default.va__lemma__svc__map__data__zeropage.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-svc_handlers.gen.dfyImpl___module.__default.va__lemma__svc__unmap__data__success.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-verify.gen.dfyImpl___module.__default.va__lemma__svc__returning__verify__inner_k.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_komodo_z3_clean--verified-verify.gen.dfyImpl___module.__default.va__lemma__svc__returning__verify.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_lvbkv_z3_clean--Betree-AsyncBetree.i.dfy.Impl__AsyncBetree.__default.QueryAdvanceChangesLookup.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_lvbkv_z3_clean--Betree-AsyncBetree_Refines_AsyncMap.i.dfy.Impl__AsyncBetree__Refines__AsyncMap.__default.RefinesNextStep.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_lvbkv_z3_clean--Betree-BetreeInv.i.dfy.Impl__BetreeInv.__default.GrowStepPreservesInvariant.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_lvbkv_z3_clean--Betree-BetreeInv.i.dfy.Impl__BetreeInv.__default.InitImpliesInv.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_lvbkv_z3_clean--Betree-BetreeInv.i.dfy.Impl__BetreeInv.__default.RedirectResultingGraph.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_lvbkv_z3_clean--Betree-Betree_Refines_Map.i.dfy.Impl__Betree__Refines__Map.__default.FlushStepRefinesMap.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_lvbkv_z3_clean--Betree-Betree_Refines_Map.i.dfy.Impl__Betree__Refines__Map.__default.GCStepRefinesMap.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_lvbkv_z3_clean--Betree-Betree_Refines_Map.i.dfy.Impl__Betree__Refines__Map.__default.GrowStepRefinesMap.txt
../mariposa/scripts/bisect-metascript.sh /home/yizhou7/mariposa/data/bisect_tasks/d_lvbkv_z3_clean--Betree-Betree_Refines_Map.i.dfy.Impl__Betree__Refines__Map.__default.InsertMessageStepRefinesMap.txt
