UNSTABLE_10_SECS = {
    "data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit__proof__helper_invariants__proof.9.smt2": "199ba4594c",
    "data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit__proof__helper_invariants__validation.3.smt2": "a1b4b3fd4a",
    "data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit__proof__liveness__daemon_set_match__lemma_from_after_get_daemon_set_step_to_after_update_daemon_set_step.smt2": "7a3bd28b48",
    "data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit__proof__liveness__resource_match__lemma_from_after_get_resource_step_to_after_update_resource_step.smt2": "0a3bc89db1",
    "data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit_config__proof__liveness__resource_match.5.smt2": "55b4af82a4",
    "data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit_config__proof__liveness__resource_match.6.smt2": "2faba7bd1f",
    "data/projs/anvil/base.z3/fluent-smt-fluent_controller__fluentbit_config__proof__liveness__resource_match__lemma_from_after_get_resource_step_to_after_create_resource_step.smt2": "68ac429152",
    "data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__helper_invariants__proof__lemma_eventually_always_every_resource_create_request_implies_at_after_create_resource_step.smt2": "634ab613c3",
    "data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__helper_invariants__proof__lemma_eventually_always_object_in_response_at_after_create_resource_step_is_same_as_etcd.smt2": "106770d98e",
    "data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__helper_invariants__validation__lemma_always_stateful_set_in_create_request_msg_satisfies_unchangeable.smt2": "48dbc6d4fa",
    "data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__liveness__resource_match.1.smt2": "621abdd996",
    "data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__liveness__resource_match__lemma_from_after_get_resource_step_to_after_update_resource_step.smt2": "65d90190b4",
    "data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__liveness__stateful_set_match__lemma_from_after_get_stateful_set_step_to_after_update_stateful_set_step.smt2": "cf8c015bcb",
    "data/projs/anvil/base.z3/zookeeper-smt-rabbitmq-smt-rabbitmq_controller__proof__liveness__stateful_set_match__lemma_stateful_set_state_matches_at_after_update_stateful_set_step.smt2": "eccd7ce2d9",
    "data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__helper_invariants__proof.2.smt2": "b475a457a9",
    "data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__helper_invariants__proof__lemma_always_no_update_status_request_msg_in_flight_of_except_stateful_set.smt2": "a7f5536a00",
    "data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__helper_invariants__proof__lemma_eventually_always_no_delete_resource_request_msg_in_flight.smt2": "b834736f4d",
    "data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__helper_invariants__validation.3.smt2": "4d2d4fbc20",
    "data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__helper_invariants__zookeeper_api__lemma_zk_request_implies_step_helper.smt2": "81b159a977",
    "data/projs/anvil/base.z3/zookeeper-smt-zookeeper_controller__proof__liveness__stateful_set_match.2.smt2": "66c9bdf69f",
    "data/projs/atmosphere/base.z3/kernel__create_and_share_pages.5.smt2": "9a3bc13b2d",
    "data/projs/flowcert/base.z3/permission.14.smt2": "93004876e4",
    "data/projs/splinterdb/base.z3/allocation_layer__LikesBetree_v.18.smt2": "2045867a58",
    "data/projs/splinterdb/base.z3/allocation_layer__LikesBetree_v__LikesBetree.3.smt2": "09d24c83cd",
    "data/projs/verismo.dedup/base.z3/allocator__linkedlist.10.smt2": "6937ca47cd",
    "data/projs/verismo.dedup/base.z3/arch__ptram__ptram_p2.smt2": "47ae6b0135",
    "data/projs/verismo.dedup/base.z3/boot__init__e820_init.2.smt2": "82449bd2e8",
    "data/projs/verismo.dedup/base.z3/boot__init__e820_init.4.smt2": "6540edb885",
    "data/projs/verismo.dedup/base.z3/boot__init__e820_init_alloc.1.smt2": "b119384805",
    "data/projs/verismo.dedup/base.z3/bsp__ap.3.smt2": "0918f4a55d",
    "data/projs/verismo.dedup/base.z3/pgtable_e__pte.18.smt2": "aad03b9358",
    "data/projs/verismo.dedup/base.z3/pgtable_e__pte.20.smt2": "8d058577cd",
    "data/projs/verismo.dedup/base.z3/security__monitor.21.smt2": "83bd54cd1a",
    "data/projs/verismo.dedup/base.z3/snp__cpuid.17.smt2": "2556504d15",
    "data/projs/verismo.dedup/base.z3/snp__ghcb__proto_page.141.smt2": "c726bffe99",
    "data/projs/verismo.dedup/base.z3/vbox__vbox.4.smt2": "f08610121f",
    "data/projs/verismo.dedup/base.z3/vbox__vbox.5.smt2": "fdfae1157a",
    "data/projs/vsystemsnew/base.z3/mimalloc-smt-commit_segment.1.smt2": "8c0bbf67d0",
    "data/projs/vsystemsnew/base.z3/mimalloc-smt-config.35.smt2": "f6f3f962c0",
    "data/projs/vsystemsnew/base.z3/mimalloc-smt-page_organization__PageOrg.69.smt2": "9eaad8947e",
    "data/projs/vsystemsnew/base.z3/mimalloc-smt-page_organization__PageOrg__impl_%4__merge_with_before_ll_inv_valid_unused.smt2": "8283ecb8b8",
    "data/projs/vsystemsnew/base.z3/mimalloc-smt-segment__segment_os_alloc.smt2": "fef99080cd",
    "data/projs/vsystemsnew/base.z3/mimalloc-smt-segment__segment_span_free_coalesce_before.smt2": "08719204aa",
    "data/projs/vsystemsnew/base.z3/mimalloc-smt-segment__span_queue_delete.smt2": "fa2fdaf6e0",
    "data/projs/vsystemsnew/base.z3/noderep-smt-spec__cyclicbuffer.3.smt2": "d057fff3f5",
    "data/projs/vsystemsnew/base.z3/noderep-smt-spec__cyclicbuffer.5.smt2": "d6181053ff",
    "data/projs/vsystemsnew/base.z3/page-table-smt-impl_u__l2_refinement.3.smt2": "c4ec60f8f9",
    "data/projs/vsystemsnew/base.z3/page-table-smt-impl_u__l2_refinement.4.smt2": "e7aff1006d",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-log__inv_v.10.smt2": "815f69b161",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-log__inv_v.12.smt2": "92c260e39d",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-log__inv_v.13.smt2": "7d8c4302ab",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-log__inv_v.14.smt2": "3c5c22d4a1",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-log__inv_v.17.smt2": "025a074d17",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-log__inv_v.2.smt2": "492704d0da",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-log__inv_v.4.smt2": "be920877ca",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-log__inv_v.5.smt2": "e1d2573021",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-log__layout_v.30.smt2": "126f0f80f3",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-log__logimpl_v.6.smt2": "a896b920ca",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__inv_v.11.smt2": "b689a8d455",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__inv_v.13.smt2": "fa9020870d",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__inv_v.14.smt2": "090a2a7d67",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__inv_v.15.smt2": "89068d3f38",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__inv_v.16.smt2": "32eaf80bcc",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__inv_v.17.smt2": "af029e0bc2",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__inv_v.2.smt2": "2078a24298",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__inv_v.7.smt2": "ed912ce861",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__inv_v.9.smt2": "c02ff41a27",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__setup_v.5.smt2": "5a940edd1b",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__setup_v.6.smt2": "568e167040",
    "data/projs/vsystemsnew/base.z3/verified-storage-smt-verified-storage-smt-storage-node-multilog__start_v.2.smt2": "e16c5e8c0b",
}

SKIP_FOR_NOW = {
    "data/projs/verismo.dedup/base.z3/arch__ptram__ptram_p2.smt2",
    "data/projs/vsystemsnew/base.z3/mimalloc-smt-page_organization__PageOrg__impl_%4__merge_with_before_ll_inv_valid_unused.smt2",
    "data/projs/vsystemsnew/base.z3/page-table-smt-impl_u__l2_refinement.4.smt2",
    "data/projs/atmosphere/base.z3/kernel__create_and_share_pages.5.smt2",
}
